-- ============================================================
-- laws_data_v3.sql — MigraGuide USA
-- Final batch: SIJS, Detention/Bonds, Worker Rights, Asylum Paths
-- Run in Supabase SQL Editor AFTER v2 files
-- ============================================================

-- ============================================================
-- SPECIAL IMMIGRANT JUVENILE STATUS (SIJS)
-- ============================================================

INSERT INTO laws (id, title, title_es, category, type, article_count, searchable_text, searchable_text_es)
VALUES
('sijs', 'Special Immigrant Juvenile Status (SIJS)', 'Estatus Especial de Inmigrante Juvenil (SIJS)', 'asylum', 'Federal Statute', 5,
 'SIJS special immigrant juvenile status minor child abuse neglect abandonment family court',
 'SIJS estatus especial inmigrante juvenil menor niño abuso negligencia abandono corte familiar')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_es = EXCLUDED.title_es, article_count = EXCLUDED.article_count;

INSERT INTO law_items (id, law_id, index, number, title, title_es, text, text_es) VALUES
('sijs-1', 'sijs', 0, 1, 'What is SIJS?', '¿Qué es SIJS?',
 'Special Immigrant Juvenile Status (SIJS) under INA §101(a)(27)(J) provides a path to a green card for children in the US who have been abused, neglected, or abandoned by one or both parents. It is one of the most important protections for vulnerable immigrant children and unaccompanied minors. SIJS leads directly to lawful permanent resident status (green card).',
 'El Estatus Especial de Inmigrante Juvenil (SIJS) bajo la INA §101(a)(27)(J) proporciona un camino hacia la tarjeta verde para niños en EE.UU. que han sido abusados, descuidados o abandonados por uno o ambos padres. Es una de las protecciones más importantes para niños inmigrantes vulnerables y menores no acompañados. SIJS conduce directamente al estatus de residente permanente legal (tarjeta verde).'),
('sijs-2', 'sijs', 1, 2, 'Eligibility Requirements', 'Requisitos de Elegibilidad',
 'To qualify for SIJS: (1) Be under 21 years of age and unmarried at the time of filing; (2) Obtain a state court order (family court, juvenile court, or probate court) finding that: (a) the child is dependent on the court or in the custody of a state agency or individual; (b) reunification with one or both parents is not viable due to abuse, neglect, abandonment, or similar basis; (c) it is not in the child''s best interest to be returned to their home country.',
 'Para calificar para SIJS: (1) Tener menos de 21 años y ser soltero al momento de presentar; (2) Obtener una orden de un tribunal estatal (corte familiar, corte juvenil o corte de sucesiones) que determine que: (a) el niño es dependiente del tribunal o está bajo custodia de una agencia estatal o individuo; (b) la reunificación con uno o ambos padres no es viable debido a abuso, negligencia, abandono o base similar; (c) no es en el mejor interés del niño ser devuelto a su país de origen.'),
('sijs-3', 'sijs', 2, 3, 'The Two-Step Process', 'El Proceso de Dos Pasos',
 'Step 1: State Court Order — File a petition in state family/juvenile court to obtain the required judicial findings (dependency, non-viability of reunification, best interest). Each state has different procedures. Step 2: USCIS Filing — File Form I-360 (Petition for Special Immigrant) with USCIS, attaching the state court order. If approved, file Form I-485 (Adjustment of Status) for the green card. There is NO filing fee for I-360 SIJS petitions.',
 'Paso 1: Orden del Tribunal Estatal — Presente una petición en la corte familiar/juvenil estatal para obtener las determinaciones judiciales requeridas (dependencia, no viabilidad de reunificación, mejor interés). Cada estado tiene procedimientos diferentes. Paso 2: Presentación ante USCIS — Presente el Formulario I-360 (Petición de Inmigrante Especial) ante USCIS, adjuntando la orden del tribunal estatal. Si se aprueba, presente el Formulario I-485 (Ajuste de Estatus) para la tarjeta verde. NO hay tarifa de presentación para peticiones SIJS I-360.'),
('sijs-4', 'sijs', 3, 4, 'Age-Out Protections', 'Protecciones contra Envejecimiento',
 'The Trafficking Victims Protection Reauthorization Act (TVPRA) provides protections against "aging out" (turning 21 before the case is resolved). Once USCIS consents to the SIJS classification, the child''s age is frozen for purposes of SIJS eligibility. However, visa availability backlogs may cause delays — certain countries (El Salvador, Guatemala, Honduras, Mexico) have long wait times for SIJS visa numbers.',
 'La Ley de Reautorización de Protección a Víctimas de Tráfico (TVPRA) proporciona protecciones contra el "envejecimiento" (cumplir 21 años antes de que el caso se resuelva). Una vez que USCIS consiente la clasificación SIJS, la edad del niño se congela para propósitos de elegibilidad SIJS. Sin embargo, los atrasos de disponibilidad de visa pueden causar demoras — ciertos países (El Salvador, Guatemala, Honduras, México) tienen tiempos de espera largos para números de visa SIJS.'),
('sijs-5', 'sijs', 4, 5, 'Important Limitations', 'Limitaciones Importantes',
 'Key limitations of SIJS: (1) SIJS green card holders CANNOT petition for their parents — this prevents parents from benefiting from the abuse/neglect/abandonment; (2) Must remain unmarried throughout the process; (3) The state court order must specifically address all three required findings; (4) USCIS has discretion to approve or deny the petition even with a favorable court order; (5) Consult an immigration attorney experienced in SIJS cases — the intersection of state and federal law is complex.',
 'Limitaciones clave de SIJS: (1) Los poseedores de tarjeta verde SIJS NO PUEDEN solicitar para sus padres — esto previene que los padres se beneficien del abuso/negligencia/abandono; (2) Debe permanecer soltero durante todo el proceso; (3) La orden del tribunal estatal debe abordar específicamente las tres determinaciones requeridas; (4) USCIS tiene discreción para aprobar o denegar la petición incluso con una orden judicial favorable; (5) Consulte un abogado de inmigración con experiencia en casos SIJS — la intersección de leyes estatales y federales es compleja.')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_es = EXCLUDED.title_es, text = EXCLUDED.text, text_es = EXCLUDED.text_es;

-- ============================================================
-- IMMIGRATION DETENTION & BONDS
-- ============================================================

INSERT INTO laws (id, title, title_es, category, type, article_count, searchable_text, searchable_text_es)
VALUES
('detention', 'Immigration Detention & Bond Rights', 'Detención Migratoria y Derechos de Fianza', 'deportation', 'Rights Guide', 5,
 'detention ICE bond hearing rights jail custody release attorney phone call',
 'detención ICE fianza audiencia derechos cárcel custodia liberación abogado llamada telefónica')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_es = EXCLUDED.title_es, article_count = EXCLUDED.article_count;

INSERT INTO law_items (id, law_id, index, number, title, title_es, text, text_es) VALUES
('det-1', 'detention', 0, 1, 'Rights During Detention', 'Derechos Durante la Detención',
 'If detained by ICE, you have the right to: (1) Know why you are being detained (ask for the charging document — NTA); (2) Remain silent — you do not have to answer questions about your immigration status; (3) Make phone calls — ICE must provide access to a phone within a reasonable time; (4) Contact your consulate (Vienna Convention); (5) Be free from physical abuse; (6) Receive necessary medical care; (7) Have access to legal materials and the law library; (8) Practice your religion.',
 'Si es detenido por ICE, tiene derecho a: (1) Saber por qué está siendo detenido (pida el documento de cargos — NTA); (2) Guardar silencio — no tiene que responder preguntas sobre su estatus migratorio; (3) Hacer llamadas telefónicas — ICE debe proporcionar acceso a un teléfono en tiempo razonable; (4) Contactar a su consulado (Convención de Viena); (5) Estar libre de abuso físico; (6) Recibir atención médica necesaria; (7) Tener acceso a materiales legales y biblioteca legal; (8) Practicar su religión.'),
('det-2', 'detention', 1, 2, 'Bond Hearings', 'Audiencias de Fianza',
 'Most detained immigrants can request a bond hearing before an immigration judge. The judge will set bond (minimum $1,500) or deny bond based on: (1) flight risk — likelihood of attending future hearings; (2) danger to the community. You can present evidence: employment records, family ties, community involvement, lack of criminal record. If bond is too high, you can request a bond redetermination. You do NOT have the right to a government-appointed attorney.',
 'La mayoría de inmigrantes detenidos pueden solicitar una audiencia de fianza ante un juez de inmigración. El juez fijará la fianza (mínimo $1,500) o denegará la fianza basándose en: (1) riesgo de fuga — probabilidad de asistir a audiencias futuras; (2) peligro para la comunidad. Puede presentar evidencia: registros de empleo, vínculos familiares, participación comunitaria, ausencia de antecedentes penales. Si la fianza es muy alta, puede solicitar una redeterminación. NO tiene derecho a un abogado designado por el gobierno.'),
('det-3', 'detention', 2, 3, 'Mandatory Detention', 'Detención Obligatoria',
 'Certain individuals are subject to mandatory detention (no bond available): (1) Aggravated felony convictions; (2) Certain drug offenses; (3) Certain firearms offenses; (4) Terrorist activity; (5) Arriving aliens in expedited removal. However, the Supreme Court ruled in Zadvydas v. Davis (2001) that the government cannot detain someone indefinitely if removal is not reasonably foreseeable. After 6 months, the detained person may challenge continued detention.',
 'Ciertas personas están sujetas a detención obligatoria (sin fianza disponible): (1) Condenas por delitos agravados; (2) Ciertos delitos de drogas; (3) Ciertos delitos de armas de fuego; (4) Actividad terrorista; (5) Extranjeros que llegan en remoción expedita. Sin embargo, la Corte Suprema dictaminó en Zadvydas v. Davis (2001) que el gobierno no puede detener a alguien indefinidamente si la remoción no es razonablemente previsible. Después de 6 meses, la persona detenida puede impugnar la detención continuada.'),
('det-4', 'detention', 3, 4, 'Finding a Detainee', 'Encontrar a un Detenido',
 'If a family member has been detained by ICE: (1) Use the ICE Online Detainee Locator System at locator.ice.gov — search by name and country of birth or A-number (alien number); (2) Call the ICE Detention Reporting and Information Line: 1-888-351-4024; (3) Contact the local ICE field office; (4) Contact your country''s consulate. Important: keep the person''s full legal name, date of birth, and A-number (if known) ready when searching.',
 'Si un familiar ha sido detenido por ICE: (1) Use el Sistema de Localización de Detenidos en línea de ICE en locator.ice.gov — busque por nombre y país de nacimiento o número A (número de extranjero); (2) Llame a la Línea de Información de Detención de ICE: 1-888-351-4024; (3) Contacte la oficina local de ICE; (4) Contacte el consulado de su país. Importante: tenga listo el nombre legal completo, fecha de nacimiento y número A (si lo conoce) al buscar.'),
('det-5', 'detention', 4, 5, 'Alternatives to Detention', 'Alternativas a la Detención',
 'ICE may release individuals under supervision through the Alternatives to Detention (ATD) program: (1) GPS ankle monitors — electronic monitoring of location; (2) SmartLINK app — a smartphone app that uses facial recognition for check-ins; (3) Telephonic reporting — regular phone check-ins with a case manager; (4) In-person reporting — periodic visits to an ICE office. Violation of ATD conditions can result in re-detention and negative consequences in removal proceedings.',
 'ICE puede liberar a individuos bajo supervisión a través del programa de Alternativas a la Detención (ATD): (1) Monitores GPS de tobillo — monitoreo electrónico de ubicación; (2) Aplicación SmartLINK — una app de teléfono que usa reconocimiento facial para registros; (3) Reporte telefónico — llamadas regulares con un administrador de caso; (4) Reporte en persona — visitas periódicas a una oficina de ICE. La violación de condiciones ATD puede resultar en re-detención y consecuencias negativas en procedimientos de remoción.')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_es = EXCLUDED.title_es, text = EXCLUDED.text, text_es = EXCLUDED.text_es;

-- ============================================================
-- WORKER RIGHTS FOR IMMIGRANTS
-- ============================================================

INSERT INTO laws (id, title, title_es, category, type, article_count, searchable_text, searchable_text_es)
VALUES
('worker-rights', 'Worker Rights for All Immigrants', 'Derechos Laborales para Todos los Inmigrantes', 'work', 'Federal Rights', 5,
 'worker rights labor protections minimum wage OSHA FLSA discrimination regardless immigration status',
 'derechos laborales protecciones trabajador salario mínimo OSHA FLSA discriminación independiente estatus migratorio')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_es = EXCLUDED.title_es, article_count = EXCLUDED.article_count;

INSERT INTO law_items (id, law_id, index, number, title, title_es, text, text_es) VALUES
('work-r-1', 'worker-rights', 0, 1, 'Rights Regardless of Status', 'Derechos Independientes del Estatus',
 'ALL workers in the US — regardless of immigration status — are protected by: (1) Fair Labor Standards Act (FLSA): minimum wage ($7.25/hr federal, higher in many states) and overtime pay; (2) Occupational Safety and Health Act (OSHA): safe working conditions; (3) National Labor Relations Act (NLRA): right to organize and join unions; (4) Title VII of the Civil Rights Act: protection from discrimination based on race, color, national origin, sex, religion. Employers CANNOT retaliate by threatening to call ICE.',
 'TODOS los trabajadores en EE.UU. — independientemente de su estatus migratorio — están protegidos por: (1) Ley de Normas Laborales Justas (FLSA): salario mínimo ($7.25/hr federal, más alto en muchos estados) y pago de horas extras; (2) Ley de Seguridad y Salud Ocupacional (OSHA): condiciones de trabajo seguras; (3) Ley Nacional de Relaciones Laborales (NLRA): derecho a organizarse y unirse a sindicatos; (4) Título VII de la Ley de Derechos Civiles: protección contra discriminación por raza, color, origen nacional, sexo, religión. Los empleadores NO PUEDEN tomar represalias amenazando con llamar a ICE.'),
('work-r-2', 'worker-rights', 1, 2, 'Wage Theft and How to Report', 'Robo de Salario y Cómo Reportar',
 'Wage theft occurs when an employer fails to pay minimum wage, overtime, or withholds pay. To report: (1) File a complaint with the Department of Labor Wage and Hour Division: 1-866-487-9243 (they do NOT ask about immigration status); (2) File with your state labor department; (3) Consult a workers'' rights attorney (many take cases on contingency). You can file a complaint even if: you are undocumented, you were paid in cash, you don''t have a written contract, or you no longer work there.',
 'El robo de salario ocurre cuando un empleador no paga salario mínimo, horas extras o retiene el pago. Para reportar: (1) Presente una queja ante la División de Horas y Salarios del Departamento de Trabajo: 1-866-487-9243 (NO preguntan sobre estatus migratorio); (2) Presente ante el departamento laboral de su estado; (3) Consulte un abogado de derechos del trabajador (muchos toman casos en contingencia). Puede presentar una queja incluso si: es indocumentado, le pagaban en efectivo, no tiene contrato escrito, o ya no trabaja ahí.'),
('work-r-3', 'worker-rights', 2, 3, 'Workplace Safety (OSHA)', 'Seguridad en el Trabajo (OSHA)',
 'OSHA protects ALL workers regardless of immigration status. You have the right to: (1) A safe workplace free from recognized hazards; (2) Training in a language you understand; (3) Safety equipment provided by the employer; (4) Report unsafe conditions without retaliation; (5) Refuse dangerous work if you believe there is imminent danger. File complaints: call OSHA at 1-800-321-OSHA (6742), online at osha.gov, or at your local OSHA office. Complaints can be filed anonymously.',
 'OSHA protege a TODOS los trabajadores independientemente del estatus migratorio. Usted tiene derecho a: (1) Un lugar de trabajo seguro libre de peligros reconocidos; (2) Capacitación en un idioma que entienda; (3) Equipo de seguridad proporcionado por el empleador; (4) Reportar condiciones inseguras sin represalias; (5) Rechazar trabajo peligroso si cree que hay peligro inminente. Presente quejas: llame a OSHA al 1-800-321-OSHA (6742), en línea en osha.gov, o en su oficina local de OSHA. Las quejas pueden presentarse de forma anónima.'),
('work-r-4', 'worker-rights', 3, 4, 'Anti-Discrimination Protections', 'Protecciones Contra Discriminación',
 'INA §274B prohibits employment discrimination based on citizenship status or national origin. Employers cannot: (1) demand specific documents — you choose which valid documents to present for I-9 verification; (2) refuse to accept valid documents; (3) retaliate against workers who assert their rights; (4) discriminate in hiring, firing, or recruitment based on national origin. Report violations to the Immigrant and Employee Rights Section (IER): 1-800-255-7688.',
 'La INA §274B prohíbe discriminación laboral basada en estatus de ciudadanía u origen nacional. Los empleadores no pueden: (1) exigir documentos específicos — usted elige qué documentos válidos presentar para verificación I-9; (2) rechazar documentos válidos; (3) tomar represalias contra trabajadores que hacen valer sus derechos; (4) discriminar en contratación, despido o reclutamiento por origen nacional. Reporte violaciones a la Sección de Derechos de Inmigrantes y Empleados (IER): 1-800-255-7688.'),
('work-r-5', 'worker-rights', 4, 5, 'Protection from Employer Retaliation', 'Protección Contra Represalias del Empleador',
 'It is ILLEGAL for employers to: (1) Report workers to ICE in retaliation for exercising labor rights; (2) Threaten to report workers to discourage complaints; (3) Fire workers for filing safety or wage complaints; (4) Use immigration status as leverage to suppress rights. If this happens: document everything, contact a workers'' rights attorney, file complaints with DOL and EEOC, and consider applying for a U visa if you are a victim of a labor crime. Many states have additional protections.',
 'Es ILEGAL que los empleadores: (1) Reporten trabajadores a ICE en represalia por ejercer derechos laborales; (2) Amenacen con reportar trabajadores para desalentar quejas; (3) Despidan trabajadores por presentar quejas de seguridad o salario; (4) Usen el estatus migratorio como palanca para suprimir derechos. Si esto sucede: documente todo, contacte un abogado de derechos del trabajador, presente quejas ante DOL y EEOC, y considere solicitar visa U si es víctima de un crimen laboral. Muchos estados tienen protecciones adicionales.')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_es = EXCLUDED.title_es, text = EXCLUDED.text, text_es = EXCLUDED.text_es;

-- ============================================================
-- ASYLUM: AFFIRMATIVE vs DEFENSIVE
-- ============================================================

INSERT INTO laws (id, title, title_es, category, type, article_count, searchable_text, searchable_text_es)
VALUES
('asylum-paths', 'Asylum: Affirmative vs Defensive Process', 'Asilo: Proceso Afirmativo vs Defensivo', 'asylum', 'Process Guide', 5,
 'asylum affirmative defensive USCIS immigration court asylum officer judge I-589 interview',
 'asilo afirmativo defensivo USCIS corte inmigración oficial asilo juez I-589 entrevista')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_es = EXCLUDED.title_es, article_count = EXCLUDED.article_count;

INSERT INTO law_items (id, law_id, index, number, title, title_es, text, text_es) VALUES
('asy-p-1', 'asylum-paths', 0, 1, 'Affirmative Asylum', 'Asilo Afirmativo',
 'Affirmative asylum is filed proactively with USCIS (you are NOT in removal proceedings). Process: (1) File Form I-589 within 1 year of arrival (free); (2) USCIS schedules an interview with an asylum officer; (3) The interview is non-adversarial — no government attorney present; (4) If approved, you receive asylum status. If not approved, the case is referred to Immigration Court for a new hearing (de novo) — you are NOT denied, just referred. Processing times: 6 months to several years.',
 'El asilo afirmativo se presenta proactivamente ante USCIS (NO está en procedimientos de remoción). Proceso: (1) Presente el Formulario I-589 dentro de 1 año de llegada (gratis); (2) USCIS programa una entrevista con un oficial de asilo; (3) La entrevista es no adversarial — no hay abogado del gobierno presente; (4) Si se aprueba, recibe estatus de asilo. Si no se aprueba, el caso es referido a la Corte de Inmigración para una nueva audiencia (de novo) — NO es denegado, solo referido. Tiempos de procesamiento: 6 meses a varios años.'),
('asy-p-2', 'asylum-paths', 1, 2, 'Defensive Asylum', 'Asilo Defensivo',
 'Defensive asylum is raised as a defense against removal in Immigration Court (you ARE in removal proceedings). Process: (1) File Form I-589 with the Immigration Court; (2) Attend a merits hearing before an immigration judge; (3) The hearing IS adversarial — a government attorney (ICE trial attorney) will cross-examine you and present evidence against your claim; (4) The judge makes the final decision. If denied, you can appeal to the Board of Immigration Appeals (BIA) within 30 days.',
 'El asilo defensivo se presenta como defensa contra la remoción en la Corte de Inmigración (ESTÁ en procedimientos de remoción). Proceso: (1) Presente el Formulario I-589 ante la Corte de Inmigración; (2) Asista a una audiencia de méritos ante un juez de inmigración; (3) La audiencia ES adversarial — un abogado del gobierno (fiscal de ICE) lo interrogará y presentará evidencia contra su reclamo; (4) El juez toma la decisión final. Si es denegado, puede apelar a la Junta de Apelaciones de Inmigración (BIA) dentro de 30 días.'),
('asy-p-3', 'asylum-paths', 2, 3, 'Key Differences', 'Diferencias Clave',
 'Affirmative: filed with USCIS, non-adversarial interview, no government attorney, asylum officer decides, if not approved → referred to court. Defensive: filed in Immigration Court, adversarial hearing with cross-examination, government attorney present, immigration judge decides, if denied → appeal to BIA. Both use the same Form I-589 and same legal standard (persecution based on 5 protected grounds). Both require filing within 1 year of arrival (with limited exceptions).',
 'Afirmativo: presentado ante USCIS, entrevista no adversarial, sin abogado del gobierno, oficial de asilo decide, si no se aprueba → referido a corte. Defensivo: presentado en Corte de Inmigración, audiencia adversarial con interrogatorio, abogado del gobierno presente, juez de inmigración decide, si se deniega → apelación a BIA. Ambos usan el mismo Formulario I-589 y el mismo estándar legal (persecución basada en 5 motivos protegidos). Ambos requieren presentación dentro de 1 año de llegada (con excepciones limitadas).'),
('asy-p-4', 'asylum-paths', 3, 4, 'Preparing Your Asylum Case', 'Preparando su Caso de Asilo',
 'Essential elements: (1) Detailed personal declaration describing the persecution you suffered or fear; (2) Country conditions evidence (State Dept reports, UNHCR, news articles); (3) Nexus: connect the harm to one of 5 protected grounds (race, religion, nationality, political opinion, particular social group); (4) Corroborating evidence (medical records, photos, police reports, death threats, affidavits from witnesses); (5) Expert witness declarations when available. The more evidence, the stronger the case.',
 'Elementos esenciales: (1) Declaración personal detallada describiendo la persecución que sufrió o teme; (2) Evidencia de condiciones del país (informes del Depto. de Estado, ACNUR, artículos de noticias); (3) Nexo: conectar el daño a uno de 5 motivos protegidos (raza, religión, nacionalidad, opinión política, grupo social particular); (4) Evidencia corroborante (registros médicos, fotos, informes policiales, amenazas de muerte, declaraciones juradas de testigos); (5) Declaraciones de testigos expertos cuando estén disponibles. Mientras más evidencia, más fuerte el caso.'),
('asy-p-5', 'asylum-paths', 4, 5, 'After Asylum is Granted', 'Después de que se Otorga el Asilo',
 'Once granted asylum: (1) You can live and work in the US indefinitely; (2) Apply for spouse and unmarried children under 21 (derivative asylum) within 2 years; (3) Apply for a green card after 1 year of asylum status (Form I-485); (4) Travel with a Refugee Travel Document (Form I-131) — do NOT return to your country of persecution, it may be seen as evidence that you no longer fear persecution; (5) After 4 years as a green card holder (5 total including the 1 year in asylum status), apply for US citizenship.',
 'Una vez otorgado el asilo: (1) Puede vivir y trabajar en EE.UU. indefinidamente; (2) Solicitar para cónyuge e hijos solteros menores de 21 (asilo derivativo) dentro de 2 años; (3) Solicitar tarjeta verde después de 1 año de estatus de asilo (Formulario I-485); (4) Viajar con un Documento de Viaje de Refugiado (Formulario I-131) — NO regrese a su país de persecución, puede verse como evidencia de que ya no teme persecución; (5) Después de 4 años como portador de tarjeta verde (5 total incluyendo el 1 año en estatus de asilo), solicitar ciudadanía estadounidense.')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_es = EXCLUDED.title_es, text = EXCLUDED.text, text_es = EXCLUDED.text_es;

-- ============================================================
-- STUDENT VISAS (F-1) — Bonus
-- ============================================================

INSERT INTO laws (id, title, title_es, category, type, article_count, searchable_text, searchable_text_es)
VALUES
('visa-student', 'Student Visas (F-1, OPT, CPT)', 'Visas de Estudiante (F-1, OPT, CPT)', 'visas', 'Visa Category', 4,
 'student visa F-1 OPT CPT SEVP I-20 university college study work STEM',
 'visa estudiante F-1 OPT CPT SEVP I-20 universidad trabajo estudio STEM')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_es = EXCLUDED.title_es, article_count = EXCLUDED.article_count;

INSERT INTO law_items (id, law_id, index, number, title, title_es, text, text_es) VALUES
('stu-1', 'visa-student', 0, 1, 'F-1 Student Visa', 'Visa de Estudiante F-1',
 'The F-1 visa allows foreign nationals to study at US academic institutions (universities, colleges, high schools, language programs). Requirements: (1) Acceptance at a SEVP-certified school; (2) Form I-20 from the school; (3) Pay SEVIS fee ($350); (4) Demonstrate sufficient funds; (5) Show non-immigrant intent (ties to home country); (6) English proficiency. F-1 students can work on-campus up to 20 hours/week during school, full-time during breaks.',
 'La visa F-1 permite a extranjeros estudiar en instituciones académicas de EE.UU. (universidades, colegios, secundarias, programas de idiomas). Requisitos: (1) Aceptación en una escuela certificada SEVP; (2) Formulario I-20 de la escuela; (3) Pagar tarifa SEVIS ($350); (4) Demostrar fondos suficientes; (5) Mostrar intención de no inmigrante (vínculos con país de origen); (6) Dominio del inglés. Los estudiantes F-1 pueden trabajar en el campus hasta 20 horas/semana durante clases, tiempo completo durante vacaciones.'),
('stu-2', 'visa-student', 1, 2, 'OPT (Optional Practical Training)', 'OPT (Capacitación Práctica Opcional)',
 'OPT allows F-1 students to work in their field of study: Pre-completion OPT: while still enrolled, up to 20 hrs/week. Post-completion OPT: after graduation, 12 months of full-time work authorization. STEM OPT Extension: students with STEM degrees can extend OPT for an additional 24 months (36 months total). File Form I-765 with USCIS. Apply 90 days before or 60 days after program end. OPT is a major pathway to H-1B sponsorship.',
 'OPT permite a estudiantes F-1 trabajar en su campo de estudio: OPT pre-completación: mientras aún está inscrito, hasta 20 hrs/semana. OPT post-completación: después de graduarse, 12 meses de autorización de trabajo a tiempo completo. Extensión STEM OPT: estudiantes con títulos STEM pueden extender OPT por 24 meses adicionales (36 meses total). Presente Formulario I-765 ante USCIS. Solicite 90 días antes o 60 días después del fin del programa. OPT es un camino importante hacia el patrocinio H-1B.'),
('stu-3', 'visa-student', 2, 3, 'CPT (Curricular Practical Training)', 'CPT (Capacitación Práctica Curricular)',
 'CPT allows F-1 students to work off-campus in internships or cooperative education that is part of the curriculum. Requirements: (1) enrolled for at least 1 academic year (except graduate programs requiring immediate CPT); (2) the work must be integral to the curriculum; (3) authorized by the school''s DSO (Designated School Official). If you use 12+ months of full-time CPT, you lose eligibility for post-completion OPT. Part-time CPT does not affect OPT eligibility.',
 'CPT permite a estudiantes F-1 trabajar fuera del campus en pasantías o educación cooperativa que es parte del currículo. Requisitos: (1) inscrito por al menos 1 año académico (excepto programas de posgrado que requieren CPT inmediato); (2) el trabajo debe ser integral al currículo; (3) autorizado por el DSO de la escuela. Si usa 12+ meses de CPT a tiempo completo, pierde elegibilidad para OPT post-completación. CPT a tiempo parcial no afecta la elegibilidad de OPT.'),
('stu-4', 'visa-student', 3, 4, 'Maintaining F-1 Status', 'Manteniendo el Estatus F-1',
 'To maintain F-1 status: (1) Attend a full course of study each semester; (2) Make normal academic progress; (3) Do NOT work off-campus without authorization; (4) Keep your I-20 valid and current; (5) Report any address changes to your DSO within 10 days; (6) Do NOT overstay your status (F-1 status ends 60 days after program completion). Violations can result in being "out of status" — which may require applying for reinstatement or leaving the US.',
 'Para mantener el estatus F-1: (1) Asista a un curso completo de estudios cada semestre; (2) Mantenga progreso académico normal; (3) NO trabaje fuera del campus sin autorización; (4) Mantenga su I-20 válido y vigente; (5) Reporte cambios de dirección a su DSO dentro de 10 días; (6) NO se quede más tiempo del permitido (el estatus F-1 termina 60 días después de completar el programa). Las violaciones pueden resultar en estar "fuera de estatus" — lo que puede requerir solicitar reinstalación o salir de EE.UU.')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, title_es = EXCLUDED.title_es, text = EXCLUDED.text, text_es = EXCLUDED.text_es;


-- ============================================================
-- Update system_metadata
-- ============================================================

UPDATE system_metadata
SET laws_last_updated = NOW(), last_upload_count = 24
WHERE id = 'main';
